openapi: 3.0.3

info:
  title: Agenda
  version: 1.0.11

externalDocs:
  description: Documentacao
  url: http://swagger.io

servers:
  - url: https://localhost:8080

tags:
  - name: pessoa
    description: Gerenciamento de pessoas

paths:
  /pessoa:
    get:
      tags:
        - pessoa
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pessoa'
        '400':
          description: ID invalido
        '404':
          description: Pessoa nao encontrada
    post:
      tags:
        - pessoa
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PessoaDto'
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pessoa'
        '405':
          description: Entrada invalida
  /pessoa/{id}:
    get:
      tags:
        - pessoa
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PessoaDto'
        '400':
          description: ID invalido
        '404':
          description: Pessoa nao encontrada
    put:
      tags:
        - pessoa
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PessoaDto'
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PessoaDto'
        '400':
          description: ID invalido
        '404':
          description: Pessoa nao encontrada
        '405':
          description: Entrada invalida
    delete:
      tags:
        - pessoa
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Sucesso
        '400':
          description: ID invalido

components:
  schemas:
    Pessoa:
      type: object
      properties:
        id:
          type: integer
          format: int32
        nome:
          type: string
        telefone:
          type: string
        email:
          type: string
        aniversario:
          type: string
          format: date
    PessoaDto:
      type: object
      properties:
        nome:
          type: string
        telefone:
          type: string
        email:
          type: string
        aniversario:
          type: string
          format: date
